'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const searchUrl=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const dirUrl=(q,mode)=>'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(q)+'&travelmode='+mode;
const link=(url,text,primary=false)=>`<a class="button ${primary?'primary':''}" href="${esc(url)}" target="_blank" rel="noopener">${esc(text)} ↗</a>`;
const placeActions=p=>`<div class="actions">${link(dirUrl(p.query,'transit'),'ניווט',true)}${link(searchUrl(p.query),'מפת גוגל')}${p.url?link(p.url,p.url.includes('getyourguide.com')?'מידע':'אתר'):''}</div>`;
function placeImage(p){return p.image?`<figure class="sitePhoto"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"><figcaption>${esc(p.name)} · מתוך מסמך הטיול</figcaption></figure>`:''}
function dateAt(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
function currentIndex(now=new Date()){const date=dateAt(now);return date<TRIP.days[0].date?0:date>TRIP.days.at(-1).date?10:TRIP.days.findIndex(d=>d.date===date)}
const dateLabel=d=>new Intl.DateTimeFormat('he-IL',{weekday:'short',day:'numeric',month:'numeric',timeZone:'UTC'}).format(new Date(d.date+'T12:00:00Z'));
let selectedDay=currentIndex(),selectedMap=selectedDay,foodPosition=null;
function paragraphHtml(text){const urgent=text.startsWith('🔴'),flex=text.startsWith('🟡'),free=text.startsWith('🟢');return `${urgent||flex||free?`<span class="badge ${urgent?'red':flex?'yellow':'green'}">${urgent?'להזמין / לבדוק':flex?'מומלץ וגמיש':'ספונטני'}</span>`:''}<p>${esc(text.replace(/^[🔴🟡🟢/]+\s*/u,''))}</p>`}
function contentBlocks(paragraphs,index){const groups=TRIP.dayGroups[index];return groups.map(([start,ids],i)=>{const rows=paragraphs.slice(start,groups[i+1]?.[0]??paragraphs.length),places=ids.map(id=>TRIP.places[id]),urls=rows.filter(p=>p.startsWith('URL:')).map(p=>p.slice(4).trim()),extra=[...new Set(urls)].filter(u=>!places.some(p=>p.url===u));return `<article class="stop">${rows.filter(p=>!p.startsWith('URL:')).map(paragraphHtml).join('')}${places.filter(p=>p.image).map(placeImage).join('')}${places.map(p=>`<div class="stopLinks">${places.length>1?`<h3>${esc(p.name)}</h3>`:''}${placeActions(p)}</div>`).join('')}${extra.length?`<div class="actions">${extra.map(u=>link(u,places.length?'מידע':'אתר')).join('')}</div>`:''}</article>`}).join('')}
function dayHtml(index){const d=TRIP.days[index];return `<div class="dayHeading"><div class="meta">${esc(dateLabel(d))} · ${TRIP.cities[d.city].name}</div><h2>${esc(d.title)}</h2><div class="actions"><button class="button primary" data-map="${index}">התחנות במפה</button><button class="button" data-food="${d.city}">אוכל באזור</button></div></div><div class="timeline">${contentBlocks(d.paragraphs,index)}</div><aside class="notice"><b>משאירים מקום לשינוי</b><p>${esc(d.plan)}</p></aside>`}
function renderDay(){ $('dayRail').innerHTML=TRIP.days.map((d,i)=>`<button class="button" data-day="${i}" aria-pressed="${i===selectedDay}">${esc(dateLabel(d))}<br>${TRIP.cities[d.city].name}</button>`).join('');$('dayDetail').innerHTML=dayHtml(selectedDay)}
function renderToday(){const i=currentIndex(),date=dateAt();$('todayStatus').textContent=date<'2026-10-01'?'הטיול הבא · 1 באוקטובר':date>'2026-10-11'?'זיכרונות מהטיול · התוכנית המלאה זמינה בימים':'היום בטיול';$('todayTitle').textContent=TRIP.days[i].title;$('todayDetail').innerHTML=dayHtml(i);loadWeather(TRIP.days[i].city)}
function renderPlaces(){const q=$('search').value.trim().toLocaleLowerCase(),city=$('cityFilter').value,cat=$('categoryFilter').value;const rows=TRIP.places.filter(p=>(city==='all'||city===p.city)&&(cat==='all'||cat===p.category)&&`${p.name} ${p.query} ${p.category} ${TRIP.cities[p.city].name}`.toLocaleLowerCase().includes(q));$('resultCount').textContent=rows.length+' מקומות';$('placeGrid').innerHTML=rows.length?rows.map(p=>`<article class="place"><span class="badge">${TRIP.cities[p.city].name} · ${esc(p.category)}</span><h3>${esc(p.name)}</h3>${placeImage(p)}<p class="muted"><bdi>${esc(p.query)}</bdi></p>${placeActions(p)}</article>`).join(''):'<div class="panel">לא נמצאו מקומות. נסו חיפוש אחר או הסירו סינון.</div>'}
function renderFood(){const city=TRIP.cities[$('nearCity').value],where=foodPosition?`${foodPosition.latitude},${foodPosition.longitude}`:city.address;$('geoStatus').textContent=foodPosition?'חיפוש סביב המיקום שנבחר. המיקום מועבר ל-Google Maps רק בפתיחת קישור.':'אזור החיפוש: '+city.address;$('foodLinks').innerHTML=[['restaurants','מסעדות'],['cafes','קפה'],['gluten free restaurants','חיפוש ללא גלוטן'],['supermarket','סופרמרקט']].map(([q,label])=>link(searchUrl(q+' near '+where),label)).join('')}
function renderMap(placeId){const ids=TRIP.days[selectedMap].stops,active=placeId??ids[0];$('mapDay').value=String(selectedMap);$('mapStops').innerHTML=ids.map((id,i)=>{const p=TRIP.places[id];return `<article class="mapStop ${id===active?'selected':''}"><button data-pin="${id}">${i+1}. ${esc(p.name)}</button>${placeActions(p)}</article>`}).join('');$('mapFrame').src='https://maps.google.com/maps?q='+encodeURIComponent(TRIP.places[active].query)+'&output=embed';$('mapFrame').title='מפה: '+TRIP.places[active].name}
function go(view){if(!['today','days','places','near','map','info'].includes(view))view='today';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('nav a').forEach(el=>{if(el.hash==='#'+view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});if(view==='map')renderMap();if(view==='near')renderFood()}
window.addEventListener('hashchange',()=>{go(location.hash.slice(1));$('main').scrollIntoView({block:'start'});$('main').focus({preventScroll:true})});
document.addEventListener('click',e=>{const day=e.target.closest('[data-day]'),map=e.target.closest('[data-map]'),food=e.target.closest('[data-food]'),pin=e.target.closest('[data-pin]');if(day){selectedDay=Number(day.dataset.day);renderDay()}if(map){selectedMap=Number(map.dataset.map);location.hash='map';renderMap()}if(food){$('nearCity').value=food.dataset.food;foodPosition=null;location.hash='near';renderFood()}if(pin)renderMap(Number(pin.dataset.pin))});
$('allDays').onclick=()=>location.hash='days';$('bookingsLink').onclick=()=>location.hash='info';$('search').oninput=renderPlaces;$('cityFilter').onchange=renderPlaces;$('categoryFilter').onchange=renderPlaces;$('nearCity').onchange=()=>{foodPosition=null;renderFood()};$('mapDay').onchange=()=>{selectedMap=Number($('mapDay').value);renderMap()};
$('locate').onclick=()=>{if(!navigator.geolocation){$('geoStatus').textContent='המכשיר אינו תומך במיקום. בחרו עיר ידנית.';return}$('geoStatus').textContent='מאתר את המיקום…';navigator.geolocation.getCurrentPosition(p=>{foodPosition=p.coords;renderFood()},()=>{$('geoStatus').textContent='המיקום לא התקבל. אפשר להמשיך לחפש לפי עיר.'},{timeout:10000,maximumAge:120000})};
let checks={};try{checks=JSON.parse(localStorage.getItem('ai-europe-2026-checklist')||'{}');if(!checks||typeof checks!=='object')checks={}}catch{}$('checklist').innerHTML=TRIP.bookings.map((b,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${checks[i]?'checked':''}><span>${esc(b)}</span></label>`).join('');$('checklist').onchange=e=>{if(!e.target.matches('[data-check]'))return;checks[e.target.dataset.check]=e.target.checked;try{localStorage.setItem('ai-europe-2026-checklist',JSON.stringify(checks));$('saveStatus').textContent='נשמר במכשיר הזה'}catch{$('saveStatus').textContent='לא ניתן לשמור בדפדפן הזה. הסימון יישמר רק עד רענון הדף.'}};
$('lodgings').innerHTML=Object.values(TRIP.cities).map(c=>`<article class="panel"><span class="badge">${c.dates}</span><h3>לינה · ${c.name}</h3><bdi>${esc(c.address)}</bdi><div class="actions">${link(searchUrl(c.address),'לכתובת במפה')}</div></article>`).join('');
const practical=[['תחבורה: המספרים במסמך אינם כרטיסים','ברלין: שדה BER נמצא באזור C. וינה: המסמך מציין עבודות בין Praterstern ל־Hauptbahnhof; לתכנן U1 ולא להסתמך על S7 ישיר לשדה. לבדוק מסלול עדכני לפני יציאה.','https://www.wien.info/en/travel-info/arrival-departure/airport-to-center/important-information-for-airport-travellers-2026-2027-1118558'],['9/10 · האופרה תלויה בכרטיסים','לפי המסמך המופע מסומן Sold Out. עם מושבים: פראטר קצר והתארגנות לאופרה. ללא מושבים: לבדוק מכירת עמידה ב־10:00; בקופה המכירה מתחילה 80 דקות לפני המופע, ללא הבטחה לכרטיס.','https://www.wiener-staatsoper.at/en/calendar/detail/il-barbiere-di-siviglia/2026-10-09/'],['11/10 · הדרך הביתה','טיסה ב־21:30 לפי המסמך; יעד הגעה לטרמינל 18:30. מסיימים בילוי ב־16:30–17:00, אוספים מזוודות ובוחרים יציאה מסוימת של VAB5. החזרה נמשכת ל־12/10.','https://www.viennaairportbus.com/en/informationen/unser-streckennetz'],['צליאק · שני תיאומים מראש','לקבל אישור מפורש מ־La Scène ומסדנת השוקולד לגבי הכנה וזיהום משני. שוקולד ללא גלוטן אינו אישור לגבי הקישוטים, הכלים או העמדה.',''],['אירועים לבחירה','Club Culture בברלין · 3–11/10; Designblok בפראג · 7–11/10; Kaiser Wiesn בווינה עד 11/10; Design District · 9–11/10. אלה התאריכים במסמך, ויש לבדוק תוכנית וזמינות באתר האירוע.','']];$('practical').innerHTML=practical.map(([title,text,url])=>`<article class="panel"><h3>${title}</h3><p>${text}</p>${url?link(url,'בדיקה באתר'):''}</article>`).join('');$('fullPlan').textContent=TRIP.source;
$('categoryFilter').insertAdjacentHTML('beforeend',[...new Set(TRIP.places.map(p=>p.category))].map(c=>`<option>${esc(c)}</option>`).join(''));$('mapDay').innerHTML=TRIP.days.map((d,i)=>`<option value="${i}">${esc(dateLabel(d))} · ${esc(d.title)}</option>`).join('');
const wx=c=>c===0?'בהיר':c<=3?'מעונן חלקית':c<=48?'ערפל':c<=67?'גשם':c<=77?'שלג':c<=86?'ממטרים':'סופות רעמים';
async function loadWeather(cityId){const city=TRIP.cities[cityId];$('weatherCity').textContent='מזג אוויר · '+city.name;try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${city.lat}&longitude=${city.lon}&current=temperature_2m,weather_code&daily=temperature_2m_max,temperature_2m_min&timezone=${encodeURIComponent(city.tz)}&forecast_days=3`;const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const j=await r.json();if(!Number.isFinite(j.current?.temperature_2m))throw Error();$('temperature').textContent=Math.round(j.current.temperature_2m)+'°';$('weatherStatus').textContent=wx(j.current.weather_code)+' · '+j.current.time.replace('T',' ');$('forecast').innerHTML=j.daily.time.map((d,i)=>`<div class="forecastRow"><span>${esc(d.slice(5).split('-').reverse().join('/'))}</span><bdi>${Math.round(j.daily.temperature_2m_min[i])}° — ${Math.round(j.daily.temperature_2m_max[i])}°</bdi></div>`).join('')}catch{$('temperature').textContent='—';$('weatherStatus').textContent='מזג האוויר אינו זמין כרגע. נסו לרענן מאוחר יותר.';$('forecast').replaceChildren()}}
document.querySelectorAll('.cityPhotos img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;img.parentElement.setAttribute('aria-label',img.alt)}));
renderToday();renderDay();renderPlaces();renderFood();go(location.hash.slice(1));
