'use strict';

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const UI={
  he:{
    pageTitle:'הטיול שלנו · שלוש ערים, טיול אחד',introEyebrow:'הטיול שלנו · אוקטובר 2026',introTitle:'שלוש ערים.\nטיול אחד.',introCities:'ברלין ← פראג ← וינה',
    allDays:'כל הימים ←',beforeTrip:'הטיול הבא · 1 באוקטובר',afterTrip:'זיכרונות מהטיול · התוכנית המלאה זמינה בימים',todayTrip:'היום בטיול',
    daysTitle:'התוכנית לפי ימים',placesTitle:'מקומות וחוויות',searchLabel:'חיפוש מקום',searchPlaceholder:'מצודה, שוק, ALIZÉ…',cityLabel:'עיר',categoryLabel:'קטגוריה',allCities:'כל הערים',allCategories:'הכול',placesCount:n=>`${n} מקומות`,noPlaces:'לא נמצאו מקומות. נסו חיפוש אחר או הסירו סינון.',
    nearTitle:'קרוב אליי',nearIntro:'חיפוש אוכל ליד הלינה או המיקום שלכם. התוצאות נפתחות ב־Google Maps.',area:'אזור',locate:'השתמשו במיקום שלי',locationUnsupported:'המכשיר אינו תומך במיקום. בחרו עיר ידנית.',locating:'מאתר את המיקום…',locationFailed:'המיקום לא התקבל. אפשר להמשיך לחפש לפי עיר.',aroundLocation:'חיפוש סביב המיקום שנבחר. המיקום מועבר ל־Google Maps רק בפתיחת קישור.',searchArea:'אזור החיפוש: ',
    restaurants:'מסעדות',cafes:'קפה',glutenFree:'חיפוש ללא גלוטן',supermarket:'סופרמרקט',gfTitle:'ללא גלוטן ≠ התאמה מאומתת לצליאק',gfText:'תוצאות Google Maps אינן אישור להתאמה. יש לברר מול המקום הכנה, כלים וזיהום משני.',
    mapTitle:'המסלול שלכם',mapDayLabel:'בחרו יום',mapIntro:'בחרו תחנה להצגה במפה. כפתורי הניווט פותחים מסלול תחבורה ציבורית בפועל.',mapNote:'ביום מעבר בין ערים, מזמינים את הרכבת בנפרד; קישור ניווט אינו כרטיס נסיעה.',noMapStops:'ליום הזה אין תחנות קבועות במפה.',mapFrame:'מפה: ',
    infoTitle:'מידע והזמנות',checklistTitle:'מה כדאי לקבע קודם',checklistIntro:'סימון אישי נשמר במכשיר ובדפדפן הזה בלבד, ואינו מבצע הזמנה.',savedHere:'נשמר במכשיר הזה',saveFailed:'לא ניתן לשמור בדפדפן הזה. הסימון יישמר רק עד רענון הדף.',accommodation:'לינה',mapAddress:'לכתובת במפה',fullPlanTitle:'תמצית התוכנית המעודכנת',sourceLink:'פתיחת מסמך Google Docs ↗',sourceNote:'האתר עודכן לפי המסמך מ־29.9.2026. שעות וזמינות עשויות להשתנות.',photoSourcesTitle:'מקורות התמונות',photoSources:'תמונות מתוך מסמך הטיול וממקורות התיירות המקושרים במסמך.',
    beforeLeaving:'לפני שיוצאים',priorityTitle:'הדברים שכדאי לסגור',priorityText:'רכבות ומקומות ישיבה, מופעים, שמירת מזוודות בווינה ואישור התאמה לצליאק.',bookingsLink:'לרשימת ההזמנות ←',priorityNote:'הסימון נשמר רק בדפדפן הזה.',weatherLoading:'טוען מזג אוויר…',weatherNote:'Open-Meteo · מזג האוויר עכשיו, לא תחזית לכל הטיול',weatherUnavailable:'מזג האוויר אינו זמין כרגע. נסו לרענן מאוחר יותר.',weatherPrefix:'מזג אוויר · ',
    navigate:'ניווט',googleMap:'מפת גוגל',website:'אתר',info:'מידע',photoFromPlan:'מתוך מסמך הטיול',mapStops:'התחנות במפה',foodArea:'אוכל באזור',urgent:'להזמין / לבדוק',flex:'מומלץ וגמיש',free:'ספונטני',optionsTitle:'אפשרויות וחלופות',showDetails:'לחצו לפרטים',changeRoom:'משאירים מקום לשינוי',
    updatesButton:'עדכונים משותפים',updatesTitle:'עדכונים משותפים',updatesIntro:'שינויים חיים מוצגים כשכבה מעל התוכנית המקורית ואינם מוחקים אותה.',updatesLoading:'בודק עדכונים…',updatesEmpty:'אין כרגע עדכונים משותפים.',updatesUnavailable:'מקור העדכונים אינו זמין כרגע. התוכנית המקורית ממשיכה לעבוד כרגיל.',editUpdates:'עריכת העדכונים ב־Google Sheets',updatesHelpTitle:'איך מוסיפים עדכון?',updatesHelp:'בגיליון Updates מוסיפים שורה עם active, date, time, status, title_he, details_he, title_en ו־details_en. משתמשים בתאריך YYYY-MM-DD וב־yes בעמודת active.',updatedForDay:'עדכון משותף ליום הזה',generalUpdate:'עדכון כללי',
    nav:{today:'היום',days:'ימים',places:'מקומות',near:'קרוב אליי',map:'מפה',info:'מידע'},switchLanguage:'Switch to English',languageButton:'EN',
    practical:[
      ['תחבורה בין הערים','הרכבת מברלין לפראג מתוכננת ל־5/10, 11:30–17:30. הרכבת מפראג לווינה מתוכננת ל־9/10, 07:40–13:00. יש להסתמך על הכרטיסים בפועל.','https://www.cd.cz/en/'],
      ['וינה · עבודות תחבורה','בין Hauptbahnhof ל־Praterstern מתכננים U1 או תחבורה עירונית. ביום החזרה אין להסתמך על S7 ישיר מ־Praterstern לשדה.','https://www.wien.info/en/travel-info/arrival-departure/airport-to-center/important-information-for-airport-travellers-2026-2027-1118558'],
      ['11/10 · הדרך הביתה','מסיימים בילוי ב־16:30–17:00, אוספים מזוודות ומכוונים להגעה לטרמינל סביב 18:30 לטיסה ב־21:30.','https://www.viennaairportbus.com/en/informationen/unser-streckennetz'],
      ['צליאק · שני תיאומים מראש','לקבל אישור מפורש מ־La Scène ומסדנת השוקולד לגבי הכנה, קישוטים, כלים וזיהום משני.',''],
      ['אירועים ושווקים לבחירה','Mauerpark ב־4/10, Farmers’ Market at Jiřák ב־8/10, Flohmarkt am Naschmarkt ב־10/10 ו־Designblok לפי העניין.','']
    ]
  },
  en:{
    pageTitle:'Our trip · Three cities, one journey',introEyebrow:'Our trip · October 2026',introTitle:'Three cities.\nOne journey.',introCities:'Berlin → Prague → Vienna',
    allDays:'All days →',beforeTrip:'Next trip · October 1',afterTrip:'Trip memories · the full itinerary is available under Days',todayTrip:'Today on the trip',
    daysTitle:'Day-by-day plan',placesTitle:'Places and experiences',searchLabel:'Search places',searchPlaceholder:'castle, market, ALIZÉ…',cityLabel:'City',categoryLabel:'Category',allCities:'All cities',allCategories:'All',placesCount:n=>`${n} places`,noPlaces:'No places found. Try another search or remove a filter.',
    nearTitle:'Near me',nearIntro:'Search for food near the accommodation or your current location. Results open in Google Maps.',area:'Area',locate:'Use my location',locationUnsupported:'This device does not support location. Choose a city manually.',locating:'Finding your location…',locationFailed:'Location was not available. You can continue searching by city.',aroundLocation:'Searching around the selected location. Your location is sent to Google Maps only when you open a link.',searchArea:'Search area: ',
    restaurants:'Restaurants',cafes:'Cafés',glutenFree:'Gluten-free search',supermarket:'Supermarket',gfTitle:'Gluten-free does not mean verified celiac-safe',gfText:'Google Maps results are not a safety confirmation. Ask the venue about preparation, utensils and cross-contamination.',
    mapTitle:'Your route',mapDayLabel:'Choose a day',mapIntro:'Choose a stop to show on the map. Navigation buttons open an actual public-transport route.',mapNote:'On travel days, train tickets are booked separately; a navigation link is not a ticket.',noMapStops:'This day has no fixed map stops.',mapFrame:'Map: ',
    infoTitle:'Information and bookings',checklistTitle:'What to confirm first',checklistIntro:'Your check marks are stored only in this browser and do not make a booking.',savedHere:'Saved on this device',saveFailed:'This browser cannot save the selection. It will last only until the page is refreshed.',accommodation:'Accommodation',mapAddress:'Open address in Maps',fullPlanTitle:'Updated itinerary summary',sourceLink:'Open the Google Docs source ↗',sourceNote:'The site was updated from the document dated September 29, 2026. Times and availability may change.',photoSourcesTitle:'Photo sources',photoSources:'Photos come from the trip document and the tourism sources linked there.',
    beforeLeaving:'Before leaving',priorityTitle:'Items to confirm',priorityText:'Intercity trains and seats, shows, luggage storage in Vienna and celiac safety confirmation.',bookingsLink:'Booking checklist →',priorityNote:'Check marks are stored only in this browser.',weatherLoading:'Loading weather…',weatherNote:'Open-Meteo · current conditions, not the forecast for the whole trip',weatherUnavailable:'Weather is unavailable right now. Try refreshing later.',weatherPrefix:'Weather · ',
    navigate:'Navigate',googleMap:'Google Maps',website:'Website',info:'Info',photoFromPlan:'from the trip document',mapStops:'Stops on the map',foodArea:'Food nearby',urgent:'Book / check',flex:'Recommended and flexible',free:'Spontaneous',optionsTitle:'Options and alternatives',showDetails:'Open for details',changeRoom:'Leave room for change',
    updatesButton:'Shared updates',updatesTitle:'Shared updates',updatesIntro:'Live changes appear above the original plan and never erase it.',updatesLoading:'Checking for updates…',updatesEmpty:'There are no shared updates right now.',updatesUnavailable:'The update source is unavailable. The original itinerary continues to work normally.',editUpdates:'Edit updates in Google Sheets',updatesHelpTitle:'How do I add an update?',updatesHelp:'In the Updates sheet, add a row with active, date, time, status, title_he, details_he, title_en and details_en. Use YYYY-MM-DD for the date and yes in the active column.',updatedForDay:'Shared update for this day',generalUpdate:'General update',
    nav:{today:'Today',days:'Days',places:'Places',near:'Near me',map:'Map',info:'Info'},switchLanguage:'החלפה לעברית',languageButton:'עברית',
    practical:[
      ['Intercity transport','The Berlin–Prague train is planned for Oct 5, 11:30–17:30. The Prague–Vienna train is planned for Oct 9, 07:40–13:00. Rely on the actual tickets.','https://www.cd.cz/en/'],
      ['Vienna · transport works','Use U1 or other city transport between Hauptbahnhof and Praterstern. On departure day, do not rely on a direct S7 from Praterstern to the airport.','https://www.wien.info/en/travel-info/arrival-departure/airport-to-center/important-information-for-airport-travellers-2026-2027-1118558'],
      ['Oct 11 · journey home','Finish sightseeing at 16:30–17:00, collect the luggage and aim to reach the terminal around 18:30 for the 21:30 flight.','https://www.viennaairportbus.com/en/informationen/unser-streckennetz'],
      ['Celiac safety · two confirmations','Obtain detailed confirmation from La Scène and the chocolate workshop about preparation, decorations, utensils and cross-contamination.',''],
      ['Optional events and markets','Mauerpark on Oct 4, Farmers’ Market at Jiřák on Oct 8, Flohmarkt am Naschmarkt on Oct 10 and Designblok if it appeals.','']
    ]
  }
};

let language='he';
try{language=localStorage.getItem('europe-trip-language')==='en'?'en':'he'}catch{}
const U=key=>UI[language][key];
const tx=value=>value&&typeof value==='object'&&!Array.isArray(value)?(value[language]??value.he??value.en??''):String(value??'');
const searchUrl=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const dirUrl=(q,mode)=>'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(q)+'&travelmode='+mode;
const link=(url,text,primary=false)=>`<a class="button ${primary?'primary':''}" href="${esc(url)}" target="_blank" rel="noopener">${esc(text)} ↗</a>`;
const getPlace=id=>TRIP.places.find(p=>p.id===id);

function placeActions(p){const externalLabel=p.urlLabel?tx(p.urlLabel):(p.url?.includes('getyourguide.com')?U('info'):U('website'));return `<div class="actions">${link(dirUrl(p.query,'transit'),U('navigate'),true)}${link(searchUrl(p.query),U('googleMap'))}${p.url?link(p.url,externalLabel):''}</div>`}
function placeImage(p){return p.image?`<figure class="sitePhoto"><img src="${esc(p.image)}" alt="${esc(tx(p.name))}" loading="lazy"><figcaption>${esc(tx(p.name))} · ${esc(U('photoFromPlan'))}</figcaption></figure>`:''}
function dateAt(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
function currentIndex(now=new Date()){const date=dateAt(now);return date<TRIP.days[0].date?0:date>TRIP.days.at(-1).date?TRIP.days.length-1:Math.max(0,TRIP.days.findIndex(d=>d.date===date))}
function dateLabel(day){return new Intl.DateTimeFormat(language==='he'?'he-IL':'en-GB',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(day.date+'T12:00:00Z'))}
let selectedDay=currentIndex(),selectedMap=selectedDay,foodPosition=null,liveUpdates=[];

function levelBadge(level){if(!level)return'';const cls=level==='urgent'?'red':level==='flex'?'yellow':'green';return `<span class="badge ${cls}">${esc(U(level))}</span>`}
function placesHtml(ids=[]){return ids.map(getPlace).filter(Boolean).map(p=>`<div class="stopLinks"><h3>${esc(tx(p.name))}</h3>${placeImage(p)}${placeActions(p)}</div>`).join('')}
function blockHtml(block){return `<article class="stop">${levelBadge(block.level)}${block.title?`<h3>${esc(tx(block.title))}</h3>`:''}${(block.text||[]).map(p=>`<p>${esc(tx(p))}</p>`).join('')}${placesHtml(block.places)}</article>`}
function optionHtml(option){const title=tx(option.title)||((option.places||[]).map(id=>tx(getPlace(id)?.name)).filter(Boolean).join(' · '));return `<details class="optionCard"><summary><span><small>${esc(U('optionsTitle'))}</small><strong>${esc(title)}</strong></span><em>${esc(U('showDetails'))}</em></summary><div class="optionBody">${(option.text||[]).map(p=>`<p>${esc(tx(p))}</p>`).join('')}${placesHtml(option.places)}${option.url?`<div class="actions">${link(option.url,U('info'))}</div>`:''}</div></details>`}
function updateCard(update,compact=false){const title=language==='en'?(update.title_en||update.title_he):(update.title_he||update.title_en);const details=language==='en'?(update.details_en||update.details_he):(update.details_he||update.details_en);const label=[update.date?formatIsoDate(update.date):'',update.time||'',update.status||''].filter(Boolean).join(' · ');return `<article class="liveUpdate ${compact?'compact':''}"><div class="updateMeta">${esc(label||U('generalUpdate'))}</div><h3>${esc(title||U('generalUpdate'))}</h3>${details?`<p>${esc(details)}</p>`:''}</article>`}
function dayUpdatesHtml(date){const rows=liveUpdates.filter(u=>u.active&&u.date===date);return rows.length?`<section class="dayUpdates"><h3>${esc(U('updatedForDay'))}</h3>${rows.map(u=>updateCard(u,true)).join('')}</section>`:''}
function dayHtml(index){const d=TRIP.days[index],options=d.options||[];return `${dayUpdatesHtml(d.date)}<div class="dayHeading"><div class="meta">${esc(dateLabel(d))} · ${esc(tx(TRIP.cities[d.city].name))}</div><h2>${esc(tx(d.title))}</h2><div class="actions"><button class="button primary" data-map="${index}">${esc(U('mapStops'))}</button><button class="button" data-food="${d.city}">${esc(U('foodArea'))}</button></div></div><div class="timeline">${d.blocks.map(blockHtml).join('')}</div>${options.length?`<section class="optionsSection"><h3>${esc(U('optionsTitle'))}</h3>${options.map(optionHtml).join('')}</section>`:''}<aside class="notice"><b>${esc(U('changeRoom'))}</b><p>${esc(tx(d.plan))}</p></aside>`}

function renderDay(){$('dayRail').innerHTML=TRIP.days.map((d,i)=>`<button class="button" data-day="${i}" aria-pressed="${i===selectedDay}">${esc(dateLabel(d))}<br>${esc(tx(TRIP.cities[d.city].name))}</button>`).join('');$('dayDetail').innerHTML=dayHtml(selectedDay)}
function renderToday(){const i=currentIndex(),date=dateAt();$('todayStatus').textContent=date<'2026-10-01'?U('beforeTrip'):date>'2026-10-11'?U('afterTrip'):U('todayTrip');$('todayTitle').textContent=tx(TRIP.days[i].title);$('todayDetail').innerHTML=dayHtml(i);$('todayUpdates').replaceChildren();loadWeather(TRIP.days[i].city)}
function categoryValue(p){return p.category.en}
function renderPlaces(){const q=$('search').value.trim().toLocaleLowerCase(),city=$('cityFilter').value,cat=$('categoryFilter').value;const rows=TRIP.places.filter(p=>p.active!==false&&(city==='all'||city===p.city)&&(cat==='all'||cat===categoryValue(p))&&`${p.name.he} ${p.name.en} ${p.query} ${p.category.he} ${p.category.en} ${TRIP.cities[p.city].name.he} ${TRIP.cities[p.city].name.en}`.toLocaleLowerCase().includes(q));$('resultCount').textContent=U('placesCount')(rows.length);$('placeGrid').innerHTML=rows.length?rows.map(p=>`<article class="place"><span class="badge">${esc(tx(TRIP.cities[p.city].name))} · ${esc(tx(p.category))}</span><h3>${esc(tx(p.name))}</h3>${placeImage(p)}<p class="muted"><bdi>${esc(p.query)}</bdi></p>${placeActions(p)}</article>`).join(''):`<div class="panel">${esc(U('noPlaces'))}</div>`}
function renderFood(){const city=TRIP.cities[$('nearCity').value],where=foodPosition?`${foodPosition.latitude},${foodPosition.longitude}`:city.address;$('geoStatus').textContent=foodPosition?U('aroundLocation'):U('searchArea')+city.address;$('foodLinks').innerHTML=[['restaurants',U('restaurants')],['cafes',U('cafes')],['gluten free restaurants',U('glutenFree')],['supermarket',U('supermarket')]].map(([q,label])=>link(searchUrl(q+' near '+where),label)).join('')}
function renderMap(placeId){const ids=TRIP.days[selectedMap].stops,active=placeId??ids[0];$('mapDay').value=String(selectedMap);if(!ids.length){$('mapStops').innerHTML=`<div class="panel">${esc(U('noMapStops'))}</div>`;$('mapFrame').removeAttribute('src');$('mapFrame').hidden=true;return}$('mapFrame').hidden=false;$('mapStops').innerHTML=ids.map((id,i)=>{const p=getPlace(id);return `<article class="mapStop ${id===active?'selected':''}"><button data-pin="${id}">${i+1}. ${esc(tx(p.name))}</button>${placeActions(p)}</article>`}).join('');const p=getPlace(active);$('mapFrame').src='https://maps.google.com/maps?q='+encodeURIComponent(p.query)+'&output=embed';$('mapFrame').title=U('mapFrame')+tx(p.name)}

function renderChecklist(){let checks={};try{checks=JSON.parse(localStorage.getItem('ai-europe-2026-checklist')||'{}');if(!checks||typeof checks!=='object')checks={}}catch{}$('checklist').innerHTML=TRIP.bookings.map((b,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${checks[i]?'checked':''}><span>${esc(tx(b))}</span></label>`).join('')}
function renderLodgings(){$('lodgings').innerHTML=Object.values(TRIP.cities).map(c=>`<article class="panel"><span class="badge">${esc(tx(c.dates))}</span><h3>${esc(U('accommodation'))} · ${esc(tx(c.name))}</h3><bdi>${esc(c.address)}</bdi><div class="actions">${link(searchUrl(c.address),U('mapAddress'))}</div></article>`).join('')}
function renderPractical(){$('practical').innerHTML=U('practical').map(([title,text,url])=>`<article class="panel"><h3>${esc(title)}</h3><p>${esc(text)}</p>${url?link(url,U('info')):''}</article>`).join('')}
function renderFullPlan(){$('fullPlan').innerHTML=TRIP.days.map(d=>`<section class="planDigest"><h3>${esc(dateLabel(d))} · ${esc(tx(d.title))}</h3>${d.blocks.flatMap(b=>b.text||[]).map(p=>`<p>${esc(tx(p))}</p>`).join('')}${d.options?.length?`<p><b>${esc(U('optionsTitle'))}:</b> ${d.options.map(o=>esc(tx(o.title))).join(' · ')}</p>`:''}</section>`).join('')}
function rebuildFilters(){const currentCity=$('cityFilter').value||'all',currentCat=$('categoryFilter').value||'all',nearCity=$('nearCity').value||'berlin';$('cityFilter').innerHTML=`<option value="all">${esc(U('allCities'))}</option>`+Object.entries(TRIP.cities).map(([id,c])=>`<option value="${id}">${esc(tx(c.name))}</option>`).join('');$('cityFilter').value=currentCity;$('categoryFilter').innerHTML=`<option value="all">${esc(U('allCategories'))}</option>`+[...new Map(TRIP.places.map(p=>[categoryValue(p),tx(p.category)])).entries()].map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('');$('categoryFilter').value=currentCat;$('nearCity').innerHTML=Object.entries(TRIP.cities).map(([id,c])=>`<option value="${id}">${esc(tx(c.name))} · ${esc(U('accommodation'))}</option>`).join('');$('nearCity').value=nearCity;$('mapDay').innerHTML=TRIP.days.map((d,i)=>`<option value="${i}">${esc(dateLabel(d))} · ${esc(tx(d.title))}</option>`).join('')}

function applyStaticTranslations(){const he=language==='he';document.documentElement.lang=language;document.documentElement.dir=he?'rtl':'ltr';document.body.classList.toggle('ltr',!he);document.title=U('pageTitle');$('introEyebrow').textContent=U('introEyebrow');$('introTitle').innerHTML=esc(U('introTitle')).replace('\n','<br>');$('introCities').textContent=U('introCities');$('allDays').textContent=U('allDays');$('daysTitle').textContent=U('daysTitle');$('placesTitle').textContent=U('placesTitle');$('searchLabel').textContent=U('searchLabel');$('search').placeholder=U('searchPlaceholder');$('cityLabel').textContent=U('cityLabel');$('categoryLabel').textContent=U('categoryLabel');$('nearTitle').textContent=U('nearTitle');$('nearIntro').textContent=U('nearIntro');$('areaLabel').textContent=U('area');$('locate').textContent=U('locate');$('gfTitle').textContent=U('gfTitle');$('gfText').textContent=U('gfText');$('mapTitle').textContent=U('mapTitle');$('mapDayLabel').textContent=U('mapDayLabel');$('mapIntro').textContent=U('mapIntro');$('mapNote').textContent=U('mapNote');$('infoTitle').textContent=U('infoTitle');$('checklistTitle').textContent=U('checklistTitle');$('checklistIntro').textContent=U('checklistIntro');$('fullPlanTitle').textContent=U('fullPlanTitle');$('sourceLink').textContent=U('sourceLink');$('sourceLink').href=TRIP.sourceUrl;$('sourceNote').textContent=U('sourceNote');$('photoSourcesTitle').textContent=U('photoSourcesTitle');$('photoSources').textContent=U('photoSources');$('priorityEyebrow').textContent=U('beforeLeaving');$('priorityTitle').textContent=U('priorityTitle');$('priorityText').textContent=U('priorityText');$('bookingsLink').textContent=U('bookingsLink');$('priorityNote').textContent=U('priorityNote');$('weatherStatus').textContent=U('weatherLoading');$('weatherNote').textContent=U('weatherNote');$('updatesButtonText').textContent=U('updatesButton');$('updatesTitle').textContent=U('updatesTitle');$('updatesIntro').textContent=U('updatesIntro');$('updatesHelpTitle').textContent=U('updatesHelpTitle');$('updatesHelp').textContent=U('updatesHelp');$('langToggle').textContent=U('languageButton');$('langToggle').setAttribute('aria-label',U('switchLanguage'));Object.entries(U('nav')).forEach(([id,text])=>document.querySelector(`[data-nav="${id}"] span`).textContent=text);rebuildFilters();renderChecklist();renderLodgings();renderPractical();renderFullPlan();renderUpdates();renderDay();renderToday();renderPlaces();renderFood();if($('map').hidden===false)renderMap()}

function formatIsoDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return value||'';return new Intl.DateTimeFormat(language==='he'?'he-IL':'en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z'))}
function renderUpdates(){const rows=liveUpdates.filter(u=>u.active).sort((a,b)=>`${a.date} ${a.time}`.localeCompare(`${b.date} ${b.time}`));$('updateCount').hidden=!rows.length;$('updateCount').textContent=String(rows.length);$('updatesList').innerHTML=rows.length?rows.map(u=>updateCard(u)).join(''):`<div class="panel emptyUpdates">${esc(U('updatesEmpty'))}</div>`;$('updatesActions').innerHTML=UPDATES_CONFIG.editUrl?link(UPDATES_CONFIG.editUrl,U('editUpdates'),true):''}
function normalActive(value){return !['','0','no','false','לא'].includes(String(value??'').trim().toLocaleLowerCase())}
function normalizeUpdateDate(value){const text=String(value??'').trim(),gv=text.match(/^Date\((\d{4}),(\d{1,2}),(\d{1,2})/);if(gv)return `${gv[1]}-${String(Number(gv[2])+1).padStart(2,'0')}-${String(gv[3]).padStart(2,'0')}`;return text}
function parseUpdateRows(headers,rows){const keys=headers.map(h=>String(h||'').trim().toLocaleLowerCase());return rows.map(row=>{const item={};keys.forEach((key,i)=>item[key]=String(row[i]??'').trim());return {active:normalActive(item.active),date:normalizeUpdateDate(item.date),time:item.time,status:item.status,title_he:item.title_he,details_he:item.details_he,title_en:item.title_en,details_en:item.details_en}}).filter(u=>u.active&&(u.title_he||u.title_en||u.details_he||u.details_en))}
function parseTextUpdates(text){const rows=text.split(/\r?\n/).map(s=>s.trim()).filter(s=>s&&!s.startsWith('#')).map(s=>s.split('|').map(v=>v.trim()));return parseUpdateRows(['active','date','time','status','title_he','details_he','title_en','details_en'],rows)}
function finishUpdates(rows){liveUpdates=rows;$('updatesStatus').textContent='';renderUpdates();renderDay();renderToday()}
window.tripUpdatesLoaded=response=>{try{if(response.status==='error'||!response.table)throw Error();const headers=response.table.cols.map(c=>c.label||c.id),keys=headers.map(h=>String(h||'').trim().toLocaleLowerCase()),rows=response.table.rows.map(r=>r.c.map((c,i)=>keys[i]==='date'?(c?.v??c?.f??''):(c?.f??c?.v??'')));finishUpdates(parseUpdateRows(headers,rows))}catch{$('updatesStatus').textContent=U('updatesUnavailable')}};
async function loadUpdates(){if(!window.UPDATES_CONFIG&&typeof UPDATES_CONFIG==='undefined')return;$('updatesStatus').textContent=U('updatesLoading');if(UPDATES_CONFIG.sheetId){document.getElementById('updatesFeed')?.remove();const script=document.createElement('script');script.id='updatesFeed';script.onerror=()=>{$('updatesStatus').textContent=U('updatesUnavailable')};script.src=`https://docs.google.com/spreadsheets/d/${encodeURIComponent(UPDATES_CONFIG.sheetId)}/gviz/tq?tqx=responseHandler:tripUpdatesLoaded&headers=1&sheet=${encodeURIComponent(UPDATES_CONFIG.sheetName)}&_=${Date.now()}`;document.head.appendChild(script);return}try{const r=await fetch(UPDATES_CONFIG.fallbackUrl,{cache:'no-store'});if(!r.ok)throw Error();finishUpdates(parseTextUpdates(await r.text()))}catch{$('updatesStatus').textContent=U('updatesUnavailable');renderUpdates()}}

function go(view){if(!['today','days','places','near','map','updates','info'].includes(view))view='today';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==view);document.querySelectorAll('nav a').forEach(el=>{if(el.hash==='#'+view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});if(view==='map')renderMap();if(view==='near')renderFood();if(view==='updates')renderUpdates()}
window.addEventListener('hashchange',()=>{go(location.hash.slice(1));$('main').scrollIntoView({block:'start'});$('main').focus({preventScroll:true})});
document.addEventListener('click',e=>{const day=e.target.closest('[data-day]'),map=e.target.closest('[data-map]'),food=e.target.closest('[data-food]'),pin=e.target.closest('[data-pin]');if(day){selectedDay=Number(day.dataset.day);renderDay()}if(map){selectedMap=Number(map.dataset.map);location.hash='map';renderMap()}if(food){$('nearCity').value=food.dataset.food;foodPosition=null;location.hash='near';renderFood()}if(pin)renderMap(Number(pin.dataset.pin))});
$('allDays').onclick=()=>location.hash='days';$('bookingsLink').onclick=()=>location.hash='info';$('updatesButton').onclick=()=>location.hash='updates';$('search').oninput=renderPlaces;$('cityFilter').onchange=renderPlaces;$('categoryFilter').onchange=renderPlaces;$('nearCity').onchange=()=>{foodPosition=null;renderFood()};$('mapDay').onchange=()=>{selectedMap=Number($('mapDay').value);renderMap()};
$('langToggle').onclick=()=>{language=language==='he'?'en':'he';try{localStorage.setItem('europe-trip-language',language)}catch{}applyStaticTranslations()};
$('locate').onclick=()=>{if(!navigator.geolocation){$('geoStatus').textContent=U('locationUnsupported');return}$('geoStatus').textContent=U('locating');navigator.geolocation.getCurrentPosition(p=>{foodPosition=p.coords;renderFood()},()=>{$('geoStatus').textContent=U('locationFailed')},{timeout:10000,maximumAge:120000})};
$('checklist').onchange=e=>{if(!e.target.matches('[data-check]'))return;let checks={};try{checks=JSON.parse(localStorage.getItem('ai-europe-2026-checklist')||'{}')}catch{}checks[e.target.dataset.check]=e.target.checked;try{localStorage.setItem('ai-europe-2026-checklist',JSON.stringify(checks));$('saveStatus').textContent=U('savedHere')}catch{$('saveStatus').textContent=U('saveFailed')}};

const weatherText={he:['בהיר','מעונן חלקית','ערפל','גשם','שלג','ממטרים','סופות רעמים'],en:['Clear','Partly cloudy','Fog','Rain','Snow','Showers','Thunderstorms']};
function weatherCode(code){const i=code===0?0:code<=3?1:code<=48?2:code<=67?3:code<=77?4:code<=86?5:6;return weatherText[language][i]}
async function loadWeather(cityId){const city=TRIP.cities[cityId];$('weatherCity').textContent=U('weatherPrefix')+tx(city.name);try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${city.lat}&longitude=${city.lon}&current=temperature_2m,weather_code&daily=temperature_2m_max,temperature_2m_min&timezone=${encodeURIComponent(city.tz)}&forecast_days=3`;const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const j=await r.json();if(!Number.isFinite(j.current?.temperature_2m))throw Error();$('temperature').textContent=Math.round(j.current.temperature_2m)+'°';$('weatherStatus').textContent=weatherCode(j.current.weather_code)+' · '+j.current.time.replace('T',' ');$('forecast').innerHTML=j.daily.time.map((d,i)=>`<div class="forecastRow"><span>${esc(formatIsoDate(d))}</span><bdi>${Math.round(j.daily.temperature_2m_min[i])}° — ${Math.round(j.daily.temperature_2m_max[i])}°</bdi></div>`).join('')}catch{$('temperature').textContent='—';$('weatherStatus').textContent=U('weatherUnavailable');$('forecast').replaceChildren()}}

document.querySelectorAll('.cityPhotos img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;img.parentElement.setAttribute('aria-label',img.alt)}));
applyStaticTranslations();go(location.hash.slice(1));loadUpdates();if(UPDATES_CONFIG.refreshMinutes>0)setInterval(loadUpdates,UPDATES_CONFIG.refreshMinutes*60000);
